package: nb_conda_kernels

platform:
  - linux-64
  - osx-64
  - win-64
  - linux-32
  - win-32

engine:
  - python=2.7
  - python=3.4
  - python=3.5

install:
  - conda config --add channels anaconda-nb-extensions

script:
  - python scripts/signal.py
  - python -c "import os; print(os.environ.get('ANE_RELEASE', 'nop'))"
  - conda build --quiet conda.recipe --no-test

build_targets: conda
