package:
  name: nb_conda_kernels
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

source:
  git_url: ../

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}string: py{{ environ.get('PY_VER').replace('.', '') }}_0
  {% else %}string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}

requirements:
  build:
    - python 2.7*|3.4*|3.5*
  run:
    - notebook >=4.2.0
    - python 2.7*|3.4*|3.5*

test:
  files:
    - package.json
    - setup.cfg
  requires:
    - coverage
    - flake8
    - freetype
    - nodejs
    - nose
    - notebook >=4.2.0
    - python 2.7*|3.4*|3.5*
    - r-essentials
    - requests
    - fontconfig # [linux]
    - mock # [py2k]

about:
  summary: Launch Jupyter kernels for any installed conda environment
  home: https://github.com/Anaconda-Platform/nb_conda_kernels
  license_file: LICENSE
  license: BSD License
